/** Dictionary namespace owned by this plugin. */
export const NS = "dsh-skins.ui";

/**
 * UI dictionaries. `zh` is the key-set source of truth; `en` must stay
 * key-complete against it (tests/dicts.test.mjs enforces this in both
 * directions, including `{placeholder}` parity).
 */
export const DICTS = {
  zh: {
    "skins.switch": "主题切换",
    "skins.title": "选择皮肤",
    "skins.official.label": "DeepSeek Harness（官方）",
    "skins.official.description": "素笺玄墨 · 留白生辉 · 本色天成",
    "appearance.title": "外观配色",
    "appearance.light": "浅色",
    "appearance.dark": "深色",
    "appearance.system": "跟随系统",
    // Personalization surface (1.0.0)
    "personalization.title": "个性化",
    "personalization.collapse": "收起个性化面板",
    "personalization.reset": "恢复默认",
    "personalization.resetJoin": "、",
    "personalization.resetConfirm": "以下设置将恢复为出厂默认：\n{fields}\n此操作立即生效，确认继续吗？",
    "personalization.light": "浅色",
    "personalization.dark": "深色",
    "personalization.builtin": "内置画作",
    "personalization.builtin.default": "默认壁纸",
    "personalization.wallpaper": "壁纸 Wallpaper",
    "personalization.slogan": "标语 Slogan",
    "personalization.panelTranslucency": "通透度 Transparency",
    "personalization.tgcf.crimson": "花城 · 银蝶灯笼",
    "personalization.tgcf.pale": "谢怜 · 云海宫阙",
    "personalization.tgcf.moonlit": "花怜 · 月下同伞（默认壁纸）",
    "personalization.openbmc.art": "左风右雷（默认壁纸）",
    "personalization.uefi.art": "集成电路（默认壁纸）",
    "personalization.meirenzhi.yuntai": "云台雅集 · 合照（默认壁纸）",
    "personalization.meirenzhi.mupeiling": "慕沛灵 · 单人",
    "personalization.meirenzhi.ziling": "紫灵 · 单人",
    "personalization.meirenzhi.nangongwan": "南宫婉 · 单人",
    "personalization.meirenzhi.nangongque": "南宫阙 · 单人",
    "personalization.meirenzhi.yinyue": "银月 · 单人",
    "personalization.library": "图库",
    "personalization.library.upload": "上传图片",
    "personalization.library.delete": "删除",
    "personalization.library.deleteConfirm": "删除后，以下皮肤的壁纸将回退为默认：",
    "personalization.library.deleteFailed": "删除失败，请重试",
    "personalization.library.deleted": "已删除：{name}",
    "personalization.library.empty": "图库为空，上传一张图片试试",
    "personalization.library.more": "还有 {count} 张未显示",
    "personalization.panelLabel": "个性化设置",
    "personalization.saveFailed": "保存失败，请重试",
    "personalization.saveConflict": "配置已在其他窗口更新，请重试",
    "personalization.library.clear": "清空图库",
    "personalization.library.clearConfirm": "将永久删除全部 {count} 张上传图片，且不可恢复。以下壁纸设置将回退为默认：{names}",
    "personalization.library.clearFailed": "部分图片删除失败，已刷新剩余列表",
    "personalization.library.uploading": "正在上传…",
    "personalization.library.uploadingBatch": "正在上传 {done}/{total}…",
    "personalization.library.uploadSomeFailed": "已上传 {ok} 张，{failed} 张失败（{reason}）",
    "personalization.library.uploadFailed": "上传失败，请重试",
    "personalization.status.loading": "正在同步个性化配置…",
    "personalization.status.offline": "配置尚未同步，暂时无法编辑",
    "personalization.status.retry": "重试",
    "personalization.status.unsupported": "配置由更新版本的插件创建，当前只读",
    "personalization.status.recovery": "检测到配置文件损坏",
    "personalization.status.recoveryHint": "可以从图片库重建配置；自定义标语与颜色等覆写可能丢失。",
    "personalization.recovery.confirm": "确认恢复",
    // Host-reported personalization errors (see host-errors.js HOST_ERROR_KEYS)
    "host.personalization.tooLarge": "图片超过大小限制",
    "host.personalization.unsupportedImage": "不支持的图片格式",
    "host.personalization.animatedWebp": "动画 WebP 暂不支持",
    "host.personalization.diskFull": "磁盘剩余空间不足",
    "host.personalization.invalidFilename": "文件展示名无效",
    "host.personalization.assetMissing": "图片不存在",
    "host.personalization.invalidConfig": "配置校验失败",
    "host.personalization.readonly": "配置为更高版本创建，当前只读",
    "host.personalization.recoveryRequired": "配置状态待恢复，请先在个性化面板确认恢复",
    "host.personalization.unknownSkin": "皮肤不存在",
    "host.personalization.uploadTimeout": "上传超时，请检查网络后重试",
  },
  en: {
    "skins.switch": "Theme Switcher",
    "skins.title": "Choose Skin",
    "skins.official.label": "DeepSeek Harness (Official)",
    "skins.official.description": "Plain paper & dark ink · breathing white space · naturally itself",
    "appearance.title": "Appearance",
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    // Personalization surface (1.0.0)
    "personalization.title": "Personalize",
    "personalization.collapse": "Collapse personalization panel",
    "personalization.reset": "Restore defaults",
    "personalization.resetJoin": ", ",
    "personalization.resetConfirm": "These settings will be reset to factory defaults:\n{fields}\nThis takes effect immediately. Continue?",
    "personalization.light": "Light",
    "personalization.dark": "Dark",
    "personalization.builtin": "Built-in artwork",
    "personalization.builtin.default": "Default wallpaper",
    "personalization.wallpaper": "Wallpaper",
    "personalization.slogan": "Slogan",
    "personalization.panelTranslucency": "Panel translucency",
    "personalization.tgcf.crimson": "Hua Cheng · Crimson & Butterflies",
    "personalization.tgcf.pale": "Xie Lian · Cloud Pavilion",
    "personalization.tgcf.moonlit": "Hualian · Moonlit Umbrella (default)",
    "personalization.openbmc.art": "Left Wind, Right Thunder (default)",
    "personalization.uefi.art": "Integrated circuit (default)",
    "personalization.meirenzhi.yuntai": "Yuntai Gathering · Group (default)",
    "personalization.meirenzhi.mupeiling": "Mu Peiling · Solo",
    "personalization.meirenzhi.ziling": "Zi Ling · Solo",
    "personalization.meirenzhi.nangongwan": "Nangong Wan · Solo",
    "personalization.meirenzhi.nangongque": "Nangong Que · Solo",
    "personalization.meirenzhi.yinyue": "Yin Yue · Solo",
    "personalization.library": "Library",
    "personalization.library.upload": "Upload image",
    "personalization.library.delete": "Delete",
    "personalization.library.deleteConfirm": "These skins will fall back to their default wallpaper:",
    "personalization.library.deleted": "Deleted: {name}",
    "personalization.library.deleteFailed": "Delete failed; try again",
    "personalization.library.empty": "Library is empty — upload an image",
    "personalization.library.more": "{count} more hidden",
    "personalization.panelLabel": "Personalization settings",
    "personalization.saveFailed": "Save failed; try again",
    "personalization.saveConflict": "Settings changed in another window; try again",
    "personalization.library.clear": "Clear library",
    "personalization.library.clearConfirm": "This permanently deletes all {count} uploaded images. These wallpaper settings fall back to defaults: {names}",
    "personalization.library.clearFailed": "Some deletions failed; the remaining list was refreshed",
    "personalization.library.uploading": "Uploading…",
    "personalization.library.uploadingBatch": "Uploading {done}/{total}…",
    "personalization.library.uploadSomeFailed": "Uploaded {ok}; {failed} failed ({reason})",
    "personalization.library.uploadFailed": "Upload failed; try again",
    "personalization.status.loading": "Syncing personalization…",
    "personalization.status.offline": "Settings not synced yet; editing is unavailable",
    "personalization.status.retry": "Retry",
    "personalization.status.unsupported": "Created by a newer plugin version; read-only",
    "personalization.status.recovery": "Configuration file is damaged",
    "personalization.status.recoveryHint": "It can be rebuilt from the image library; custom slogans and colors may be lost.",
    "personalization.recovery.confirm": "Confirm recovery",
    // Host-reported personalization errors (see host-errors.js HOST_ERROR_KEYS)
    "host.personalization.tooLarge": "Image exceeds the size limit",
    "host.personalization.unsupportedImage": "Unsupported image format",
    "host.personalization.animatedWebp": "Animated WebP is not supported",
    "host.personalization.diskFull": "Not enough disk space",
    "host.personalization.invalidFilename": "Invalid display name",
    "host.personalization.assetMissing": "Image not found",
    "host.personalization.invalidConfig": "Configuration failed validation",
    "host.personalization.readonly": "Created by a newer config version; read-only",
    "host.personalization.recoveryRequired": "Configuration needs recovery; confirm it in the personalization panel first",
    "host.personalization.unknownSkin": "Skin not found",
    "host.personalization.uploadTimeout": "Upload timed out; check your connection and retry",
  },
};

/**
 * Format helper shared by the switcher and the personalization panel: substitutes
 * `{name}` placeholders, leaving unknown ones untouched (mirrors the
 * official locale runtime's `translate` behaviour).
 */
export function formatTemplate(template, params = {}) {
  return Object.entries(params).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
